/* Extra route modules. Edit this file when adding road stops or shopping. */
(() => {
  const byId = id => window.TRIP_DATA.find(stop => stop.id === id);
  const tirana = byId('tirana');
  tirana.arrival.text = 'Ожидаемый вечерний прилёт LY5183 в TIA — около 21:20; время нужно сверить с EL AL. Для группы из восьми заранее закажите минивэн или две машины у Speed Taxi, Blue Taxi, Lux Taxi либо трансфер отеля. Ориентир обычной машины — 1 500–2 200 ALL (€15–22), 25–35 минут; цену минивэна подтвердите при заказе. Официальное AHA Taxi работает круглосуточно. Автобус до площади Скандербега ходит каждый час 24/7, 400 ALL с человека (3 200 ALL на восьмерых), но затем остаётся около 2 км до отеля — поздно вечером он менее практичен.';
  tirana.shopping = [
    {name:'Tirana East Gate (TEG)', icon:'🛍️', note:'Лучший выбор международных брендов в Тиране: Zara, H&M, Mango, Massimo Dutti, Timberland, Nike, Adidas, Reebok, Geox, LC Waikiki и детские линии. Удобно совместить с Dajti; до центра — такси.', brands:'Outdoor/обувь · дети · масс-маркет', hours:'Обычно 10:00–22:00; проверить перед поездкой.', website:'https://www.teg.al/', map:'https://www.google.com/maps/search/?api=1&query=Tirana+East+Gate'},
    {name:'Toptani Shopping Center', icon:'🛍️', note:'Центральный торговый центр примерно с 80 магазинами, кафе и игровой зоной наверху. Удобнее всего без машины, во время прогулки по центру.', brands:'Одежда · дети · кафе', hours:'Обычно ежедневно 09:00–21:00.', website:'https://www.toptani.com.al/en', map:'https://www.google.com/maps/search/?api=1&query=Toptani+Shopping+Center'}
  ];
  const mavrovo = byId('mavrovo');
  mavrovo.journeyStops = [
    {icon:'🏰', name:'Круя · альтернативный маршрут без Косово', timing:'сначала 3–3,5 часа до Круи', stay:'1,5–2 часа', detail:'Круя находится не на быстром маршруте через Косово: это отдельный южный вариант через Тирану и заметно удлиняет день. Не сочетать с Призреном. Короткий круг: Старый базар → замок → панорамная площадка у стен; музей Скандербега добавит ещё около часа.', map:'https://www.google.com/maps/search/?api=1&query=Kruja+Castle', website:'https://www.akt.gov.al/en/culture/Kruja-Castle-a/', sights:[{name:'Старый базар',map:'https://www.google.com/maps/search/?api=1&query=Old+Bazaar+Kruje'},{name:'Замок Круи',map:'https://www.google.com/maps/search/?api=1&query=Kruja+Castle'},{name:'Панорама от крепостных стен',map:'https://www.google.com/maps/search/?api=1&query=Kruja+Castle+Viewpoint'}]},
    {icon:'🍲', name:'Призрен · Shadërvan и Besimi Beska', timing:'примерно через 3–3,5 часа', stay:'75–90 минут', detail:'Первая полноценная пауза: короткий круг по старому центру и семейный обед в известном ресторане традиционной кухни. Парковку лучше искать на краю пешеходного центра.', website:'https://beskarestaurant.com/en', map:'https://www.google.com/maps/search/?api=1&query=Besimi+Beska+Prizren'},
    {icon:'🕌', name:'Тетово · Расписная мечеть', timing:'примерно через 2,5–3 часа после Призрена', stay:'30–45 минут', detail:'Красивый и короткий культурный перерыв перед последним участком. Нужна закрытая одежда; во время молитвы не мешать посетителям. Перекус или ранний ужин — в городе.', map:'https://www.google.com/maps/search/?api=1&query=Painted+Mosque+Tetovo'},
    {icon:'🛍️', name:'Palma Mall Tetovo · запасной быстрый стоп', timing:'10 минут от центра Тетово', stay:'45–75 минут', detail:'Практичный вариант с туалетами, быстрым питанием и магазинами, если дети устали или погода плохая. Это не outlet village и выбор брендов скромнее, чем в Скопье.', website:'https://palmamall.mk/', map:'https://www.google.com/maps/search/?api=1&query=Palma+Mall+Tetovo'}
  ];
  mavrovo.shopping = [
    {name:'Palma Mall Tetovo', icon:'🛍️', note:'Удобен прямо по маршруту для еды и базовых покупок; выбор международных outdoor-брендов ограничен.', brands:'Повседневная одежда · обувь · еда', hours:'Проверить актуальные часы.', website:'https://palmamall.mk/', map:'https://www.google.com/maps/search/?api=1&query=Palma+Mall+Tetovo'},
    {name:'Skopje East Gate Mall · только при осознанном крюке', icon:'🛍️', note:'Самый сильный выбор брендов: более 220 магазинов, Zara, Massimo Dutti, Tommy Hilfiger, Adidas, Nike, Intersport и The Athlete’s Foot. Есть большой food court, но заезд в Скопье заметно удлинит и без того тяжёлый день.', brands:'Outdoor/спорт · дети · международные бренды', hours:'Обычно 10:00–22:00; проверить.', website:'https://eastgatemall.mk/en/brand/', map:'https://www.google.com/maps/search/?api=1&query=East+Gate+Mall+Skopje'}
  ];
  const ohrid = byId('ohrid');
  ohrid.pois.push({name:'Via Ferrata Dobroja',icon:'🧗',teaser:'Открытая феррата C/D с панорамой Охридского озера',duration:'3–5 часов с логистикой',age:'Взрослые · с гидом',description:'Маршрут в национальном парке Галичица: 535 м страховочного троса, около 145 м вертикального лазания и три секции 40, 52 и 53 м. Последняя секция C/D — наиболее силовая; между секциями предусмотрены безопасные выходы. Для двух относительно новых участников разумно идти с профессиональным гидом и заранее согласовать возможность закончить после первых двух секций.',parking:'Старт от пикниковой зоны Korita. Оттуда около 1,2 км и 20–30 минут пешком до начала; тропа подхода местами размечена слабо.',hours:'Закладывать половину дня и стартовать утром. Не идти при дожде, грозе, мокрой скале или сильном ветре.',watch:'Нужны каска, обвязка и сертифицированный комплект via ferrata с амортизатором; обычные карабины не заменяют его. Последний участок имеет нависание и требует силы рук. Hiking in Macedonia предлагает гида и прокат комплекта — бронировать заранее.',map:'https://www.google.com/maps/search/?api=1&query=Korita+Picnic+Area+Galicica',nav:'https://www.google.com/maps/dir/?api=1&destination=40.9711,20.8211',website:'https://ferrataguide.com/ferrata/Dobroja',resources:[{label:'Гид и прокат комплекта',url:'https://www.hikinginmacedonia.com/tour/via-ferrata-dobroja/'},{label:'Место получения · уточнить у оператора',url:'https://www.google.com/maps/search/?api=1&query=Hiking+in+Macedonia+Ohrid'}],food:[]});
  const gjirokaster = byId('gjirokaster');
  gjirokaster.journeyStops = [{icon:'🌿',name:'Пермeт · город и долина Вьосы',timing:'вариант маршрута через Корчу',stay:'1,5–2 часа в городе · 3–4 часа с Bënjë',detail:'Красивый, но более медленный вариант переезда. Для короткой паузы: набережная → City Stone с видом на город и Вьосу → центральная площадь. Термальные источники Bënjë, мост Кадиу и каньон Лангарица находятся вне города и требуют отдельного крюка; их стоит выбирать только вместо других планов дня.',website:'https://www.akt.gov.al/en/cities/allows/',map:'https://www.google.com/maps/search/?api=1&query=Permet+Albania',sights:[{name:'City Stone · городской вид',map:'https://www.google.com/maps/search/?api=1&query=Guri+i+Qytetit+Permet'},{name:'Вид на долину Вьосы',map:'https://www.google.com/maps/search/?api=1&query=Vjosa+River+Viewpoint+Permet'},{name:'Bënjë и мост Кадиу · только с запасом времени',map:'https://www.google.com/maps/search/?api=1&query=Kadiut+Bridge+Benje'}]}];
  const saranda = byId('saranda');
  saranda.pois.push({name:'Корфу на пароме',icon:'⛴️',teaser:'Самостоятельная однодневная поездка в Грецию',duration:'Полный день',age:'Для всех',description:'Пассажирский паром или Flying Dolphin связывает порт Саранды с городом Корфу. Переход занимает примерно 30 минут на скоростном судне или 1 ч 15 мин на обычном. На Корфу удобно пройти Старую крепость, Liston и улочки старого города; автомобиль лучше оставить в Саранде.',parking:'Оставить машину на охраняемой парковке возле порта и прийти на международный терминал заранее. Уточните у прокатчика, можно ли оставлять автомобиль на ночь, если планы изменятся.',hours:'По опубликованному расписанию Finikas на 21.07–30.09.2026 из Саранды ежедневно: 06:00, 08:30, 09:45, 10:30, 12:30, 13:30, 15:45, 18:30, 20:00; обратно с Корфу: 08:00, 09:00, 11:00, 12:30, 13:30, 16:00, 18:15, 19:00, 23:00. Время и тип судна перепроверить при бронировании.',watch:'Это международная граница: паспорта нужны всем восьмерым. Приехать минимум за 60 минут, а в августе бронировать заранее. Греция на час впереди Албании; расписание обычно указывается в местном времени каждого порта. Скоростные суда чувствительнее к ветру и могут отменяться.',map:'https://www.google.com/maps/search/?api=1&query=Saranda+Ferry+Terminal',nav:'https://www.google.com/maps/dir/?api=1&destination=Saranda+Ferry+Terminal',website:'https://finikas-lines.com/',food:[{name:'Corfu Old Town',note:'Liston и Старый город — удобная зона для обеда; выбирать по свежим отзывам в день поездки.',map:'https://www.google.com/maps/search/?api=1&query=Restaurants+Corfu+Old+Town'}]});
})();
