/* Единственный файл, который нужно менять при обновлении маршрута. */
window.TRIP_DATA = [
  {
    id: "tirana", number: "01", city: "Тирана", country: "Албания", dates: "13–15 августа", nights: "2 ночи", hotel: "F&M Hotel 2", transport: "Такси · автобус · пешком",
    intro: "Энергичная столица, где османское прошлое, бетонные бункеры и яркая современная архитектура помещаются в одной прогулке. Город стал столицей Албании в 1920 году, а сегодня его серые фасады превратились в цветной городской эксперимент.",
    weather: { high: "31–35°", low: "19–22°", rain: "Низкая", feel: "Очень жарко", note: "Улицу планировать до 11:00 и после 17:00; вода и головные уборы обязательны." },
    arrival: { title: "Поздний прилёт · LY5183", text: "Ожидаемый вечерний прилёт в TIA — около 21:20, но время нужно сверить с EL AL. Для семьи из четырёх человек лучше заранее заказать Speed Taxi, Blue Taxi или Lux Taxi: ориентир 1 500–1 800 ALL (€15–19), 25–35 минут. Официальное AHA Taxi — около 2 200 ALL, круглосуточно. Автобус до площади Скандербега ходит каждый час 24/7 и стоит 400 ALL с человека, но затем потребуется ещё около 2 км до отеля.", links: [{label:"Автобус TIA",url:"https://www.tirana-airport.com/en/transport-and-directions/15/By-Bus"},{label:"Официальное такси",url:"https://www.tirana-airport.com/en/article/13/By-Taxi"}] },
    pois: [
      { name:"Dajti Ekspres", icon:"🚡", teaser:"Канатная дорога, панорама и развлечения на горе", duration:"4–5 часов", age:"6+", description:"Длинный подъём над восточной частью города ведёт на плато Дайти, где заметно прохладнее. Наверху — обзорные площадки, мини-гольф и приключенческий парк.", parking:"Не нужен: от центра удобнее местное такси до нижней станции. Если всё же ехать на машине, парковка есть у станции.", hours:"Проверить сезонное расписание и выходной день перед визитом; приезжать к открытию.", watch:"В жару взять воду и крем; на вершине может быть прохладный ветер. Adventure Park имеет отдельные ограничения по росту.", map:"https://www.google.com/maps/search/?api=1&query=Dajti+Ekspres", nav:"https://www.google.com/maps/dir/?api=1&destination=Dajti+Ekspres", website:"https://dajtiekspres.com/", food:[{name:"Ballkoni Dajtit",note:"Панорамный обед наверху",web:"https://dajtiekspres.com/",map:"https://www.google.com/maps/search/?api=1&query=Ballkoni+Dajtit"}] },
      { name:"Grand Park", icon:"🌳", teaser:"Озеро, площадки, велосипеды и вечерняя прохлада", duration:"2–3 часа", age:"Для всех", description:"Главная зелёная зона Тираны площадью почти 290 гектаров. Хорошее место для спокойного первого дня после перелёта.", parking:"Из Blloku удобно дойти пешком или доехать коротким такси.", hours:"Открытая парковая территория; лучше рано утром или после 18:00.", watch:"Не планировать длинную прогулку в полуденную жару. У воды следить за детьми на необорудованных участках.", map:"https://www.google.com/maps/search/?api=1&query=Grand+Park+of+Tirana", nav:"https://www.google.com/maps/dir/?api=1&destination=Grand+Park+of+Tirana", food:[{name:"Era Vila",note:"Албанская кухня и понятные детские блюда",web:"https://era.al/",map:"https://www.google.com/maps/search/?api=1&query=Era+Vila+Tirana"},{name:"Juvenilja Castelo",note:"Большой семейный ресторан рядом с парком",map:"https://www.google.com/maps/search/?api=1&query=Juvenilja+Castelo+Tirana"}] },
      { name:"Пирамида и центр", icon:"🏙️", teaser:"Современная Тирана, площадь и закат с Пирамиды", duration:"2–3 часа", age:"Для всех", description:"Бывший музей Энвера Ходжи переосмыслен как открытая городская площадка. Отсюда легко пройти к площади Скандербега и Новому базару.", parking:"Пешком из отеля; автомобиль в центре только усложнит маршрут.", hours:"Пирамида снаружи доступна свободно; на закате бывает людно.", watch:"Ступени высокие и открытые — младшего ребёнка держать рядом. Покрытие нагревается на солнце.", map:"https://www.google.com/maps/search/?api=1&query=Pyramid+of+Tirana", nav:"https://www.google.com/maps/dir/?api=1&destination=Pyramid+of+Tirana", food:[{name:"Era Blloku",note:"Надёжный семейный вариант рядом с отелем",web:"https://era.al/",map:"https://www.google.com/maps/search/?api=1&query=Era+Blloku"}] },
      { name:"Bunk’Art 1", icon:"🕳️", teaser:"Подземный бункер и история XX века", duration:"1,5–2 часа", age:"Лучше 9+", description:"Огромный противоатомный комплекс превращён в музей диктатуры и повседневной жизни коммунистической Албании.", parking:"Удобно совместить с Dajti Ekspres; объекты находятся в одной части города.", hours:"Проверить последний вход на официальном сайте.", watch:"Темно, прохладно и местами эмоционально тяжело. Для шестилетнего ребёнка посещение можно сократить или пропустить.", map:"https://www.google.com/maps/search/?api=1&query=BunkArt+1+Tirana", nav:"https://www.google.com/maps/dir/?api=1&destination=BunkArt+1+Tirana", website:"https://bunkart.al/", food:[{name:"Jarna Traditional Restaurant",note:"Албанская кухня в районе Дайти",map:"https://www.google.com/maps/search/?api=1&query=Jarna+Traditional+Restaurant+Tirana"}] }
    ]
  },
  {
    id:"theth", number:"02", city:"Тет", country:"Албания", dates:"15–19 августа", nights:"4 ночи", hotel:"Villa Molla", transport:"Автомобиль · пешком",
    intro:"Высокогорная долина в Албанских Альпах, веками изолированная перевалами. Каменная церковь, башня примирения и традиционные гостевые дома сохранили ощущение отдельного маленького мира.",
    weather:{high:"23–28°",low:"13–17°",rain:"Грозы возможны",feel:"Свежие вечера",note:"Погода меняется быстро: закрытая обувь, дождевик и тёплый слой должны быть в рюкзаке."},
    pois:[
      {name:"Водопад Грунас",icon:"💦",teaser:"Лучший семейный поход из деревни",duration:"3–4 часа",age:"6+",description:"Короткий горный маршрут к водопаду высотой около 25–30 метров. Достаточно приключений для детей, но без масштаба перевального похода.",parking:"Если стартовать из центра Тета, автомобиль не нужен. Уточните у хозяев Villa Molla ближайший безопасный выход на тропу.",hours:"Выходить утром; формального режима работы нет.",watch:"Камни у воды скользкие, края каньона не огорожены. После дождя маршрут оценить заново.",map:"https://www.google.com/maps/search/?api=1&query=Grunas+Waterfall+Theth",nav:"https://www.google.com/maps/dir/?api=1&destination=Grunas+Waterfall+Theth",food:[{name:"Blue River Bar & Grill",note:"Удобно после прогулки",map:"https://www.google.com/maps/search/?api=1&query=Blue+River+Bar+Grill+Theth"},{name:"Bar Restaurant Jezerca",note:"Местная кухня и виды",map:"https://www.google.com/maps/search/?api=1&query=Bar+Restaurant+Jezerca+Theth"}]},
      {name:"Blue Eye из Nderlysaj",icon:"🔵",teaser:"Бирюзовый источник и серьёзный семейный день",duration:"4–6 часов",age:"Уверенные 6+",description:"Лесная тропа и каменистый подъём ведут к ярко-синему холодному источнику. Для детей это большой поход, а не короткая прогулка.",parking:"Ехать до Nderlysaj и оставлять машину на обозначенной платной площадке у начала маршрута.",hours:"Стартовать не позже 08:30, чтобы избежать жары и основного потока.",watch:"Тропа местами крутая и скользкая; купание ледяное. Отменить при грозе или если младший устал после предыдущего похода.",map:"https://www.google.com/maps/search/?api=1&query=Blue+Eye+Theth",nav:"https://www.google.com/maps/dir/?api=1&destination=Blue+Eye+Theth",food:[{name:"Lulash Zelna",note:"Гриль и пицца у начала маршрута",map:"https://www.google.com/maps/search/?api=1&query=Lulash+Zelna+Nderlysaj"}]},
      {name:"Деревня и Lock-in Tower",icon:"⛪",teaser:"Спокойный день среди истории долины",duration:"2–3 часа",age:"Для всех",description:"Церковь Тета, каменная башня примирения, река и луга образуют лёгкий маршрут для дня приезда или восстановления.",parking:"Оставить машину у жилья и пройти пешком.",hours:"Внутренний осмотр башни зависит от присутствия смотрителя.",watch:"Носите наличные: карты и связь в долине работают нестабильно.",map:"https://www.google.com/maps/search/?api=1&query=Lock+in+Tower+Theth",nav:"https://www.google.com/maps/dir/?api=1&destination=Lock+in+Tower+Theth",food:[{name:"Petriti Restaurant",note:"Семейный ресторан в центре деревни",map:"https://www.google.com/maps/search/?api=1&query=Petriti+Restaurant+Theth"}]}
    ],
    warning:"Перевалы Valbona и Peja не включены: это длинные, сложные и местами неогороженные маршруты. Для детей 6 и 9 лет разумнее долина, Грунас и Blue Eye только по самочувствию."
  },
  {
    id:"mavrovo",number:"03",city:"Маврово",country:"Северная Македония",dates:"19–20 августа",nights:"1 ночь",hotel:"Lakeview Hotel & Apartments",transport:"Автомобиль",
    intro:"Крупнейший национальный парк Северной Македонии объединяет озеро, горы Бистра и старые горные деревни. Его самый узнаваемый символ — церковь Святого Николая, которую уровень водохранилища то скрывает, то возвращает суше.",
    weather:{high:"22–27°",low:"11–15°",rain:"Локальные грозы",feel:"Прохладно вечером",note:"После жаркой Албании температура у озера обманчиво низкая — держите ветровки под рукой."},
    pois:[
      {name:"Озеро и старая церковь",icon:"⛪",teaser:"Лёгкая остановка после длинной дороги",duration:"1–2 часа",age:"Для всех",description:"Прогулка вдоль водохранилища к Старой церкви Святого Николая — главная открытка Маврово и подходящий формат на одну ночь.",parking:"Небольшие площадки вдоль дороги; не перекрывать частные въезды.",hours:"Свободный внешний осмотр; доступ к церкви зависит от уровня воды.",watch:"Берег местами илистый и без ограждений. Это не лучший участок озера для купания детей.",map:"https://www.google.com/maps/search/?api=1&query=Old+Mavrovo+Church",nav:"https://www.google.com/maps/dir/?api=1&destination=Old+Mavrovo+Church",food:[{name:"Mavrovski Merak",note:"Высоко оценённая македонская кухня",map:"https://www.google.com/maps/search/?api=1&query=Mavrovski+Merak"},{name:"Restaurant Kula",note:"Удобно на северной стороне озера",map:"https://www.google.com/maps/search/?api=1&query=Restaurant+Kula+Mavrovo"}]},
      {name:"Водопад Duf",icon:"🥾",teaser:"Лесная прогулка возле Rostuše",duration:"2–3 часа",age:"6+",description:"Тенистая тропа через лес и каньон к небольшому водопаду — хороший бонус, только если семья отдохнула после переезда.",parking:"Парковаться в Rostuše у начала отмеченной тропы, не заезжая на узкие жилые улицы.",hours:"Идти только при дневном свете.",watch:"Последний участок бывает мокрым и скользким; при позднем приезде полностью исключить.",map:"https://www.google.com/maps/search/?api=1&query=Duf+Waterfall",nav:"https://www.google.com/maps/dir/?api=1&destination=Duf+Waterfall",food:[{name:"House of the Mijaks",note:"Региональная кухня по пути",map:"https://www.google.com/maps/search/?api=1&query=House+of+the+Mijaks"}]}
    ]
  },
  {
    id:"ohrid",number:"04",city:"Охрид",country:"Северная Македония",dates:"20–23 августа",nights:"3 ночи",hotel:"Villa Mina",transport:"Автомобиль · лодка",
    intro:"Один из древнейших городов региона стоит у озера возрастом в миллионы лет. Средневековый Охрид был важным центром славянской письменности; его культурный и природный ландшафт охраняется ЮНЕСКО.",
    weather:{high:"27–31°",low:"16–19°",rain:"Обычно сухо",feel:"Тёплый бриз",note:"Для крепости нужна защита от солнца; вечером у воды пригодится тонкий слой."},
    pois:[
      {name:"Старый город и Канео",icon:"🌅",teaser:"Деревянный настил, озеро и знаменитая церковь",duration:"3–4 часа",age:"Для всех",description:"Маршрут через старые улицы и настил над водой заканчивается у церкви Святого Иоанна Канео — одного из лучших видов поездки.",parking:"Оставить машину на официальной парковке у входа в старый город; узкие улицы внутри не подходят для поиска места.",hours:"Начать утром или ближе к закату.",watch:"Много ступеней, скользкая брусчатка и открытые края у обзорных точек.",map:"https://www.google.com/maps/search/?api=1&query=Church+of+Saint+John+at+Kaneo",nav:"https://www.google.com/maps/dir/?api=1&destination=Church+of+Saint+John+at+Kaneo",food:[{name:"Kaneo Letna Bavcha",note:"Терраса у воды, рейтинг около 4,4",map:"https://www.google.com/maps/search/?api=1&query=Kaneo+Letna+Bavcha"},{name:"Kaj Kanevche",note:"Рыба и вид на озеро",map:"https://www.google.com/maps/search/?api=1&query=Kaj+Kanevche"}]},
      {name:"Крепость Самуила",icon:"🏰",teaser:"Башни, стены и панорама города",duration:"1,5–2 часа",age:"6+",description:"Средневековая крепость на вершине холма превращает историю в настоящее исследование стен и башен.",parking:"Использовать парковку старого города и объединить с прогулкой к Канео.",hours:"Проверить летние часы; приезжать к открытию.",watch:"Почти нет тени, неровные ступени и высокие стены. В полдень слишком жарко.",map:"https://www.google.com/maps/search/?api=1&query=Samuel's+Fortress+Ohrid",nav:"https://www.google.com/maps/dir/?api=1&destination=Samuel's+Fortress+Ohrid",food:[{name:"The Lion Ohrid",note:"Большое семейное меню, рейтинг около 4,7",map:"https://www.google.com/maps/search/?api=1&query=The+Lion+Ohrid"}]},
      {name:"Bay of Bones",icon:"🛖",teaser:"Поселение на сваях над прозрачной водой",duration:"1,5–2 часа",age:"Для всех",description:"Реконструкция доисторического поселения делает археологию наглядной: дома стоят на деревянных сваях прямо над озером.",parking:"Официальная парковка у музея; удобная остановка по дороге к Святому Науму.",hours:"Проверить летнее расписание и последний вход.",watch:"Настилы над водой требуют внимания к младшему ребёнку. Тени мало.",map:"https://www.google.com/maps/search/?api=1&query=Bay+of+Bones+Museum",nav:"https://www.google.com/maps/dir/?api=1&destination=Bay+of+Bones+Museum",website:"https://muzejohrid.mk/",food:[{name:"Restaurant Dva Bisera",note:"Рыба и македонская кухня по пути",map:"https://www.google.com/maps/search/?api=1&query=Restaurant+Dva+Bisera+Ohrid"}]},
      {name:"Святой Наум и источники",icon:"🛶",teaser:"Монастырь, павлины и тихая лодка по источникам",duration:"3–5 часов",age:"Для всех",description:"Монастырский комплекс у границы с Албанией дополняет короткая прогулка на весельной лодке по прозрачным источникам.",parking:"Большая платная парковка перед комплексом; сохранить билет до выезда.",hours:"Приехать до туристических автобусов или после 15:00.",watch:"Лодка оплачивается отдельно; заранее уточнить наличие детских жилетов. Не кормить павлинов с рук.",map:"https://www.google.com/maps/search/?api=1&query=Monastery+Saint+Naum",nav:"https://www.google.com/maps/dir/?api=1&destination=Monastery+Saint+Naum",food:[{name:"Ostrovo",note:"На территории источников",map:"https://www.google.com/maps/search/?api=1&query=Restaurant+Ostrovo+Saint+Naum"}]}
    ]
  },
  {
    id:"gjirokaster",number:"05",city:"Гирокастра",country:"Албания",dates:"23–24 августа",nights:"1 ночь",hotel:"Sharm Hotel Luxury / Villa Sharm",transport:"Автомобиль · пешком",
    intro:"«Каменный город» поднимается по склону под огромной крепостью. Османские дома-крепости с каменными крышами сделали исторический центр объектом ЮНЕСКО; здесь родился писатель Исмаил Кадаре.",
    weather:{high:"32–36°",low:"15–20°",rain:"Очень низкая",feel:"Сухая жара",note:"Крепость — только к открытию; с 13:00 до 17:00 лучше отдыхать."},
    pois:[
      {name:"Крепость Гирокастры",icon:"🏰",teaser:"Стены, пушки, самолёт и вид на долину",duration:"2–3 часа",age:"6+",description:"Огромная цитадель над городом хранит военную экспозицию и захваченный американский самолёт — сильный интерес для детей этого возраста.",parking:"Официальные площадки у верхней части старого города быстро заполняются. Приехать до 09:00 и не пытаться ехать глубоко по узкой брусчатке.",hours:"Проверить часы и кассу накануне; территория музея может закрываться раньше внешних частей.",watch:"Очень мало тени, неровный камень и открытые перепады. Взять больше воды, чем кажется необходимым.",map:"https://www.google.com/maps/search/?api=1&query=Gjirokaster+Castle",nav:"https://www.google.com/maps/dir/?api=1&destination=Gjirokaster+Castle",food:[{name:"Taverna Kardhashi",note:"Традиционная семейная кухня выше крепости",map:"https://www.google.com/maps/search/?api=1&query=Taverna+Tradicionale+Kardhashi"},{name:"Castle View Grill",note:"Небольшая терраса с видом",map:"https://www.google.com/maps/search/?api=1&query=Castle+View+Grill+Gjirokaster"}]},
      {name:"Старый базар и дом Скендули",icon:"🏠",teaser:"Живой османский дом и каменные улицы",duration:"2–3 часа",age:"Для всех",description:"Дом Скендули показывает устройство большой османской семьи лучше обычного музея. После — короткая прогулка по базару.",parking:"Оставить автомобиль там же, где для крепости; весь район проходится пешком.",hours:"Экскурсии по дому могут проводиться хозяевами; иметь наличные.",watch:"Брусчатка очень скользкая в гладкой обуви. Выбрать только один исторический дом, чтобы не утомлять детей.",map:"https://www.google.com/maps/search/?api=1&query=Skenduli+House",nav:"https://www.google.com/maps/dir/?api=1&destination=Skenduli+House",food:[{name:"Çoku Restaurant Pizzeria",note:"Удобное меню с детьми у базара",map:"https://www.google.com/maps/search/?api=1&query=Coku+Restaurant+Pizzeria+Gjirokaster"}]},
      {name:"Cold War Tunnel",icon:"🔦",teaser:"Подземный комплекс времён диктатуры",duration:"45–60 минут",age:"Лучше 9+",description:"Сеть помещений, построенная для руководства города на случай ядерной атаки. Сильное, но мрачное дополнение к истории Албании.",parking:"Идти пешком из старого города.",hours:"Вход обычно только с сопровождающим — расписание уточнить в день визита.",watch:"Темно, сыро и эмоционально тяжело; младший ребёнок может отказаться. Нужна закрытая обувь.",map:"https://www.google.com/maps/search/?api=1&query=Cold+War+Tunnel+Gjirokaster",nav:"https://www.google.com/maps/dir/?api=1&destination=Cold+War+Tunnel+Gjirokaster",food:[]}
    ]
  },
  {
    id:"saranda",number:"06",city:"Саранда",country:"Албания",dates:"24–29 августа",nights:"5 ночей",hotel:"Mucobega Hotel 2",transport:"Автомобиль · лодка",
    intro:"Южный курорт вырос вокруг естественной бухты напротив Корфу. Рядом лежит античный Бутринт — город, в котором последовательно жили греки, римляне, византийцы и венецианцы.",
    weather:{high:"30–33°",low:"19–23°",rain:"Очень низкая",feel:"Тёплое море",note:"Аквашузы, тент и защита от солнца важнее дополнительной одежды."},
    pois:[
      {name:"Бутринт",icon:"🏛️",teaser:"Античный город, крепость и природа",duration:"3–4 часа",age:"6+",description:"Лучший исторический объект юга: театр, ворота, базилика и крепость образуют почти приключенческий маршрут через тенистый лес.",parking:"Большая парковка перед входом, но к 10:00 образуется очередь на узкой подъездной дороге.",hours:"Приехать к открытию; билеты и актуальные часы проверить на официальном ресурсе.",watch:"Маршрут неровный, после дождя скользкий. В августе возможны комары; взять репеллент и воду.",map:"https://www.google.com/maps/search/?api=1&query=Butrint+National+Park",nav:"https://www.google.com/maps/dir/?api=1&destination=Butrint+National+Park",website:"https://butrint.al/",food:[{name:"The Mussel House",note:"Мидии у озера по дороге из Бутринта",web:"https://www.themusselhouse.com/",map:"https://www.google.com/maps/search/?api=1&query=The+Mussel+House+Ksamil"}]},
      {name:"Ксамиль",icon:"🏖️",teaser:"Бирюзовая вода и короткие переправы к островкам",duration:"Полдня",age:"Для всех",description:"Самые узнаваемые пляжи региона. Детям подходят спокойная вода и короткие лодочные переправы, но август — пик сезона.",parking:"Выбрать конкретный пляж и парковку заранее; не въезжать в центр без плана. Лучше прибыть до 08:30.",hours:"Пляжи открыты свободно, лежаки платные и цены меняются по зонам.",watch:"Очень многолюдно, музыка и тесная парковка. Сначала согласовать цену лежаков; не оставлять вещи без присмотра.",map:"https://www.google.com/maps/search/?api=1&query=Ksamil+Beach",nav:"https://www.google.com/maps/dir/?api=1&destination=Ksamil+Beach",food:[{name:"Abiori",note:"Ресторан у воды; бронировать",map:"https://www.google.com/maps/search/?api=1&query=Abiori+Ksamil"},{name:"Island Restaurant & Pizza",note:"Простые блюда для детей",map:"https://www.google.com/maps/search/?api=1&query=Island+Restaurant+Pizza+Ksamil"}]},
      {name:"Blue Eye",icon:"💧",teaser:"Мощный источник невероятного цвета",duration:"2–3 часа",age:"Для всех",description:"Прозрачный карстовый источник по дороге между Гирокастрой и Саранда. Логичнее посетить в день переезда, если выехать рано.",parking:"Официальная парковка находится перед пешеходным участком; до источника идти по открытой дороге.",hours:"Приехать утром до экскурсионных групп.",watch:"Парковка и вход платные; от солнца почти негде спрятаться. Купание запрещено и вода очень холодная.",map:"https://www.google.com/maps/search/?api=1&query=The+Blue+Eye+Albania",nav:"https://www.google.com/maps/dir/?api=1&destination=The+Blue+Eye+Albania",food:[{name:"Restaurant Syri i Kaltër",note:"Удобно, но туристические цены",map:"https://www.google.com/maps/search/?api=1&query=Restaurant+Syri+i+Kalter"}]},
      {name:"Лекурси на закате",icon:"🌇",teaser:"Панорама Саранды и Корфу",duration:"1,5–2 часа",age:"Для всех",description:"Короткий автомобильный подъём к крепости ради широкого вида на бухту, Ксамиль и Корфу.",parking:"Парковка у ресторана; в час заката возможна очередь на узкой дороге.",hours:"Приехать минимум за 45 минут до заката.",watch:"Еда дороже, чем в городе; бронировать столик с видом заранее или приехать только на панораму.",map:"https://www.google.com/maps/search/?api=1&query=Lekuresi+Castle",nav:"https://www.google.com/maps/dir/?api=1&destination=Lekuresi+Castle",food:[{name:"Lekursi Castle Restaurant",note:"Главное преимущество — вид",map:"https://www.google.com/maps/search/?api=1&query=Lekursi+Castle+Restaurant"},{name:"Haxhi",note:"Рыба и мясо в центре Саранды",map:"https://www.google.com/maps/search/?api=1&query=Haxhi+Saranda"},{name:"Taverna Fish Filipi",note:"Неформальный рыбный ужин",map:"https://www.google.com/maps/search/?api=1&query=Taverna+Fish+Filipi+Saranda"}]},
      {name:"Лодочный день",icon:"⛵",teaser:"Небольшие пляжи и море без парковки",duration:"5–7 часов",age:"Для всех",description:"Групповая или частная лодка позволяет добраться до бухт, куда сложнее приехать на автомобиле.",parking:"Оставить автомобиль у отеля и уточнить точную точку посадки на набережной.",hours:"Подтвердить отправление и возвращение вечером накануне.",watch:"Выбирать судно с тентом, туалетом и детскими жилетами нужного размера. Отменить при сильном ветре, даже если оператор готов выйти.",map:"https://www.google.com/maps/search/?api=1&query=Saranda+Boat+Tours",nav:"https://www.google.com/maps/dir/?api=1&destination=Saranda+Port",food:[]}
    ]
  }
];
