/* English content layer. It mirrors trip-data.js and keeps links/ratings in sync. */
(() => {
  const en = JSON.parse(JSON.stringify(window.TRIP_DATA));
  const top = {
    tirana:{city:'Tirana',country:'Albania',dates:'13–15 August',nights:'2 nights',transport:'Taxi · bus · walking',intro:'A lively capital where Ottoman traces, Cold War bunkers and bold contemporary architecture fit into one walk. Tirana became Albania’s capital in 1920; its once-grey façades are now a colourful urban experiment.',weather:{high:'31–35°',low:'19–22°',rain:'Low',feel:'Very hot',note:'Plan outdoor time before 11:00 and after 17:00; water and hats are essential.'}},
    theth:{city:'Theth',country:'Albania',dates:'15–19 August',nights:'4 nights',transport:'Car · walking',intro:'A high Alpine valley isolated by mountain passes for centuries. Its stone church, lock-in tower and traditional guesthouses still feel like a small world of their own.',weather:{high:'23–28°',low:'13–17°',rain:'Thunderstorms possible',feel:'Cool evenings',note:'Weather changes fast: carry proper shoes, a rain shell and a warm layer.'}},
    mavrovo:{city:'Mavrovo',country:'North Macedonia',dates:'19–20 August',nights:'1 night',transport:'Car',intro:'North Macedonia’s largest national park combines a lake, the Bistra mountains and old highland villages. Its icon is St Nicholas Church, alternately surrounded by water and dry land.',weather:{high:'22–27°',low:'11–15°',rain:'Local storms',feel:'Cool after sunset',note:'The lake feels much colder than Albania; keep windbreakers handy.'}},
    ohrid:{city:'Ohrid',country:'North Macedonia',dates:'20–23 August',nights:'3 nights',transport:'Car · walking · boat',intro:'One of Europe’s oldest lake settlements, shaped by Byzantine churches, medieval fortifications and a clear ancient lake shared by two countries.',weather:{high:'27–31°',low:'16–19°',rain:'Occasional storm',feel:'Hot in the sun',note:'Sightsee early, swim later, and keep a light layer for boat rides.'}},
    gjirokaster:{city:'Gjirokastër',country:'Albania',dates:'23–25 August',nights:'2 nights',transport:'Car · walking',intro:'A dramatic Ottoman stone town climbing a steep hillside below its fortress. Slate roofs and fortified houses earned it the name “City of Stone”.',weather:{high:'30–35°',low:'18–21°',rain:'Low',feel:'Very hot',note:'Use grippy shoes on the polished cobbles and avoid the castle at midday.'}},
    saranda:{city:'Sarandë',country:'Albania',dates:'25–29 August',nights:'4 nights',transport:'Car · boat',intro:'A bright Ionian base for beaches, ancient Butrint and the springs of the south. The seafront is modern, while major archaeological sites sit within an easy drive.',weather:{high:'29–33°',low:'21–24°',rain:'Mostly dry',feel:'Hot and humid',note:'Start early, reserve shade on beach days and watch the wind before boat trips.'}}
  };
  const pois = {
    tirana:[
      ['Dajti Ekspres','Cable car, panorama and mountain activities','A long cable-car ride reaches the cooler Dajti plateau with viewpoints, mini-golf and an adventure park.','Take a local taxi to the lower station; parking is available if needed.','Check the seasonal timetable and weekly closing day; arrive at opening.','Bring water and sunscreen. The rope park has separate height restrictions.','6+','4–5 hours'],
      ['Grand Park','Lake, playgrounds, bikes and evening shade','Tirana’s main green space is ideal for an easy first day after the flight.','Walk from Blloku or take a short taxi.','Go early or after 18:00.','Avoid a long midday walk and supervise children closely beside open water.','All ages','2–3 hours'],
      ['Pyramid and city centre','Modern Tirana, the main square and sunset steps','The former Enver Hoxha museum is now an open urban landmark, easily combined with Skanderbeg Square and the New Bazaar.','Walk from the hotel; a car makes the centre harder.','Outside access is generally open; sunset is busy.','The high open steps become hot—keep the youngest children close.','All ages','2–3 hours'],
      ["Bunk’Art 1",'A vast underground Cold War museum','A huge nuclear bunker now explains dictatorship and everyday life in communist Albania.','Combine it with Dajti Ekspres in the same part of town.','Check the final admission time online.','Dark, cool and emotionally heavy; shorten or skip for younger children.','Best for 9+','1.5–2 hours']
    ],
    theth:[
      ['Grunas Waterfall','The best family hike from the village','A short mountain route to a 25–30 m waterfall: adventurous without the scale of a pass crossing.','Leave the car at the lodging and confirm the safest trail access.','Start in the morning; there are no formal opening hours.','Wet rocks are slippery and gorge edges are unfenced. Reassess after rain.','6+','3–4 hours'],
      ['Blue Eye from Nderlysaj','A turquoise spring and a serious family hike','A forest trail and rocky climb reach the intensely blue, ice-cold spring. This is a substantial hike for children.','Use the marked paid parking at the Nderlysaj trailhead.','Start by 08:30.','Steep and slippery in places; cancel for storms or accumulated fatigue.','Confident hikers 6+','4–6 hours'],
      ['Village and Lock-in Tower','An easy historical recovery day','Link the church, lock-in tower, river and meadows in a gentle village walk.','Leave the car at the accommodation.','Tower entry depends on the caretaker being present.','Carry cash; cards and mobile service can be unreliable.','All ages','2–3 hours'],
      ['Valbona Pass summit and return','Climb from Theth to the pass and return the same way','A demanding 16–20 km return day with roughly 1,050–1,200 m ascent to the 1,795 m saddle. Hire a local guide.','Leave the car at the lodging and confirm the marked trail access.','Start at 05:30–06:00; strict turnaround by 11:00–11:30.','Not a normal family walk. For the youngest children, use only a partial climb to a viewpoint. Attempt the pass only with proven endurance and perfect weather.','Only very experienced children','8–10 hours'],
      ['Peja Pass — partial hike','Scenic lower trail, returning before the steep scree','The full route is about 14 km and 1,000 m ascent. The family plan is 1.5–2 hours up the lower valley, turning back before the open, loose upper slope.','Start on foot from Theth; agree a turnaround point with a guide or host.','Leave around 07:00 and return before midday heat.','The upper pass is steep, exposed and unsuitable for young children. Turn back for cloud or fatigue.','8+ for the partial route','3–4 hours']
    ],
    mavrovo:[
      ['Lake and Old Church','A gentle stop after the longest drive','Walk by the reservoir to the partially submerged Old St Nicholas Church, Mavrovo’s signature view.','Use small roadside pull-offs without blocking driveways.','Outside viewing is free; access depends on water level.','The shore can be muddy and unfenced; it is not the best children’s swimming spot.','All ages','1–2 hours'],
      ['Duf Waterfall','A shaded forest walk near Rostuše','A forest-and-gorge trail to a small waterfall, only if everyone still has energy after the drive.','Park in Rostuše near the marked trailhead.','Daylight only.','The final section can be wet and slippery; skip after a late arrival.','6+','2–3 hours']
    ],
    ohrid:[
      ['Old Town and Kaneo','Boardwalk, lake and Ohrid’s famous church','Old lanes and the waterside boardwalk end at St John at Kaneo, one of the trip’s finest views.','Use official parking at the edge of the old town.','Start early or near sunset.','Expect many steps, polished stone and open viewpoints.','All ages','3–4 hours'],
      ["Samuel’s Fortress",'Walls, towers and a broad city panorama','The hilltop medieval fortress turns history into an exploration of ramparts and towers.','Use old-town parking and combine with Kaneo.','Check summer hours; arrive at opening.','Little shade, uneven steps and high walls make midday a poor choice.','6+','1.5–2 hours'],
      ['Bay of Bones','A prehistoric stilt village above clear water','A reconstructed settlement makes archaeology tangible, with wooden houses built directly over the lake.','Official parking is beside the museum.','Check summer hours and last admission.','Supervise younger children on the open boardwalks; shade is limited.','All ages','1.5–2 hours'],
      ['St Naum and the springs','Monastery, peacocks and a quiet rowing boat','Combine the lakeside monastery with a short rowing-boat trip through crystal-clear springs.','Large paid car park before the complex.','Arrive before tour buses or after 15:00.','Boats cost extra; confirm child-size life jackets and do not hand-feed peacocks.','All ages','3–5 hours']
    ],
    gjirokaster:[
      ['Gjirokastër Castle','Walls, artillery, an aircraft and valley views','The immense citadel contains military exhibits and a captured aircraft—high-interest history for these ages.','Upper-town parking fills quickly; arrive before 09:00.','Check ticket office and museum hours the day before.','Very little shade, rough stone and open drops; carry plenty of water.','6+','2–3 hours'],
      ['Old Bazaar and Skenduli House','A living Ottoman house and stone streets','Skenduli House explains how a large Ottoman household lived; follow with a short bazaar walk.','Keep the car in the same parking used for the castle.','House tours may be hosted by the owners; carry cash.','Cobbles are extremely slippery in smooth footwear. Choose one historic house only.','All ages','2–3 hours'],
      ['Cold War Tunnel','An underground command complex','A sombre network built for the city leadership in case of nuclear attack.','Walk from the old town.','Entry is usually guided; confirm times that day.','Dark, damp and emotionally heavy; younger children may prefer to skip it.','Best for 9+','45–60 minutes']
    ],
    saranda:[
      ['Butrint','Ancient city, fortress and nature','The south’s essential historical site: theatre, gates, basilica and fortress form an adventurous shaded circuit.','Large car park by the gate; the access road queues after 10:00.','Arrive at opening and verify current hours online.','Uneven and slippery after rain; bring repellent and water.','6+','3–4 hours'],
      ['Ksamil','Turquoise water and tiny island crossings','Calm water and short boat hops work well for children, but August is peak season.','Choose the exact beach and parking before leaving; arrive by 08:30.','Beach access is open; sunbeds are paid and prices vary.','Crowds, loud music and tight parking: agree sunbed prices first.','All ages','Half day'],
      ['Blue Eye','A powerful spring of extraordinary colour','A clear karst spring best visited during the transfer from Gjirokastër if the group leaves early.','Official parking precedes a sunny pedestrian approach.','Arrive before tour groups.','Parking and entry are paid; swimming is prohibited and the water is very cold.','All ages','2–3 hours'],
      ['Lëkurësi at sunset','Panorama over Sarandë and Corfu','A short drive to the castle for a broad sunset view over the bay, Ksamil and Corfu.','Restaurant parking; expect a queue near sunset.','Arrive at least 45 minutes before sunset.','Food costs more for the view; reserve or visit only for the panorama.','All ages','1.5–2 hours'],
      ['Boat day','Small beaches without the parking problem','A group or private boat reaches coves that are awkward by car.','Leave cars at the hotel and confirm the exact waterfront boarding point.','Reconfirm departure and return the evening before.','Choose shade, a toilet and four correct child-size life jackets; cancel in strong wind.','All ages','5–7 hours']
    ]
  };
  en.forEach(stop => {
    Object.assign(stop, top[stop.id]);
    if (stop.transfer) {
      const transfers={theth:['Tirana → Theth','3 hr 30 min – 4 hr 30 min','≈170 km','Allow another 30–45 minutes for stops and Shkodër traffic; the final section is winding.'],mavrovo:['Theth → Mavrovo','≈6 hr 30 min – 8 hr','route depends on border permissions','The quickest route may cross Kosovo and two borders. Get written rental and insurance approval for every country and every vehicle.'],ohrid:['Mavrovo → Ohrid','1 hr 30 min – 2 hr','≈100 km','Mountain roads can be slow; do not schedule a fixed-time activity on arrival.'],gjirokaster:['Ohrid → Gjirokastër','4 hr 30 min – 6 hr','≈240 km','Allow for the Qafë Thanë border, breaks and summer traffic.'],saranda:['Gjirokastër → Sarandë','1 hr 15 min – 1 hr 45 min','≈55 km','The Blue Eye is a logical stop if leaving early; add 2–3 hours including walking.']};
      const t=transfers[stop.id]; if(t) stop.transfer={from:t[0],time:t[1],distance:t[2],note:t[3]};
    }
    stop.pois.forEach((p,i)=>{const x=pois[stop.id][i]; Object.assign(p,{name:x[0],teaser:x[1],description:x[2],parking:x[3],hours:x[4],watch:x[5],age:x[6],duration:x[7]}); p.food?.forEach(f=>f.note='Well-regarded nearby option; recheck recent reviews and booking needs.');});
  });
  en[0].arrival={title:'Late arrival · LY5183',text:'Expected evening arrival at TIA is around 21:20; verify with EL AL. For eight travellers, pre-book a minivan or two cars from Speed Taxi, Blue Taxi, Lux Taxi or the hotel. A regular car is roughly 1,500–2,200 ALL (€15–22), 25–35 minutes; confirm the minivan fare. The 24/7 city bus is 400 ALL each (3,200 ALL for eight) and still leaves about 2 km to the hotel, so it is less practical late at night.',links:en[0].arrival.links.map((x,i)=>({...x,label:i?'Official taxi':'TIA bus'}))};
  en[0].activities=[{icon:'🚲',name:'Grand Park family bike loop',detail:'45–90 minutes on the flatter main path. Confirm four suitable children’s bikes and helmets in advance.'},{icon:'🧗',name:'Dajti Adventure Park',detail:'Rope courses near the upper cable-car station. Check height limits and wind closures.'}];
  en[1].activities=[{icon:'⚡',name:'Thethi Zipline',detail:'A short popular valley activity; verify minimum height/weight and weather operation.'},{icon:'🚲',name:'Cycling only as a local option',detail:'The mountain road is too steep and mixed with traffic for the youngest children. Consider only a short flat valley section with helmets.'}];
  en[2].activities=[{icon:'🛶',name:'Kayak or SUP on the lake',detail:'Choose calm morning water, correct child-size life jackets and stay near shore.'},{icon:'🚲',name:'Short lakeside ride',detail:'Ask locally for a low-traffic section and suitable children’s bikes; avoid fast main-road stretches.'}];
  en[1].warning='The full Valbona Pass return and full Peja Pass are not ordinary family walks. Use a local guide, start early and agree a shorter fallback that works for all four children.';
  en[2].journeyStops=[
    {icon:'🍲',name:'Prizren · Shadërvan and Besimi Beska',timing:'after roughly 3–3.5 hours',stay:'75–90 minutes',detail:'A proper first break: walk a short old-town loop and eat traditional food at a well-known family restaurant. Park outside the pedestrian core.',website:'https://beskarestaurant.com/en',map:'https://www.google.com/maps/search/?api=1&query=Besimi+Beska+Prizren'},
    {icon:'🕌',name:'Tetovo · Painted Mosque',timing:'roughly 2.5–3 hours after Prizren',stay:'30–45 minutes',detail:'A beautiful short cultural pause before the final leg. Dress modestly and avoid disturbing worshippers.',map:'https://www.google.com/maps/search/?api=1&query=Painted+Mosque+Tetovo'},
    {icon:'🛍️',name:'Palma Mall Tetovo · quick fallback',timing:'10 minutes from central Tetovo',stay:'45–75 minutes',detail:'Useful for toilets, quick food and bad weather. It is not an outlet village and brand choice is more limited than Skopje.',website:'https://palmamall.mk/',map:'https://www.google.com/maps/search/?api=1&query=Palma+Mall+Tetovo'}
  ];
  en[0].shopping=[{name:'Tirana East Gate (TEG)',icon:'🛍️',note:'Tirana’s best international-brand selection: Zara, H&M, Mango, Timberland, Nike, Adidas, Reebok, Geox and children’s lines.',brands:'Outdoor/footwear · children · high street',hours:'Usually 10:00–22:00; verify.',website:'https://www.teg.al/',map:'https://www.google.com/maps/search/?api=1&query=Tirana+East+Gate'},{name:'Toptani Shopping Center',icon:'🛍️',note:'Central mall with about 80 shops, food and a children’s play area. Easy to combine with the city-centre walk.',brands:'Clothing · children · food',hours:'Usually daily 09:00–21:00.',website:'https://www.toptani.com.al/en',map:'https://www.google.com/maps/search/?api=1&query=Toptani+Shopping+Center'}];
  en[2].shopping=[{name:'Palma Mall Tetovo',icon:'🛍️',note:'Convenient on the route for food and basic shopping; limited specialist outdoor selection.',brands:'Casual clothing · shoes · food',hours:'Verify current hours.',website:'https://palmamall.mk/',map:'https://www.google.com/maps/search/?api=1&query=Palma+Mall+Tetovo'},{name:'Skopje East Gate Mall · deliberate detour only',icon:'🛍️',note:'The strongest brand selection: 220+ stores including Zara, Tommy Hilfiger, Adidas, Nike, Intersport and The Athlete’s Foot, plus a large food court. The Skopje detour makes an already long day longer.',brands:'Outdoor/sport · children · international brands',hours:'Usually 10:00–22:00; verify.',website:'https://eastgatemall.mk/en/brand/',map:'https://www.google.com/maps/search/?api=1&query=East+Gate+Mall+Skopje'}];
  window.TRIP_DATA_EN=en;
})();
